module.exports = {
	writeCommentInline: '${emoji.pencil2}',
	writeNewCommentInline: '${emoji.speech_balloon}${emoji.pencil2}',
	commentsCountInline: '${emoji.speech_balloon}',
	abbr1k: 'K',
	abbr1m: 'M',
	Post: 'Postagem',
	from: 'de',
	channel: 'canal',
	linkIcon: '${emoji.globe_with_meridians}',
	linkImage: '${emoji.frame_with_picture}',
	Back: 'Voltar',
	toTred: 'para o tópico ${emoji.speech_balloon}',
	AnswerToUser: 'Resposta',
	pencilIcon: '${emoji.pencil2}',
	utc: 'utc',
	trashCanIcon: '${emoji.wastebasket}',
	ReplyFromTred: 'Resposta ao tópico',
	OpenTred: 'Abrir tópico',
	commentsIcon: '${emoji.speech_balloon}',
	NewComment: 'Novo comentário',
	Tip: 'Dica',
	AboutTime: 'horário de UTC ${emoji.globe_with_meridians}',
	textDelimiter: '  |  ',
	DeletedByUser: '[apagado pelo usuário]',
	DeletedByAdmin: '[apagado pelo administrador]',
	DeletedUsername: '[usuário]',
	TredLevel: 'Nível do tópico',
	byComment: 'por comentário',
	SubscribeSettings: 'Configurações de inscrição',
	SubscribeSettingsBell: '${emoji.bell}'
}
